services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: dev-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    networks:
      - default

volumes:
  postgres_data: